amun/swagger.yaml

When used references, swagger-codegen mixes models and the do not correspond to
the correct semantics.

Separate models for swagger-codegen

---

amun/api_v1.py
amun/swagger.yaml

It will be much nicer from user PoV to provide one endpoint for gathering
information about statuses - for both job and build statuses

Provide only one status endpoint

---

amun/inspect.py

Without this, the child process was unable to capture stdandard error output to
opened file and failed with non-zero exit code causing inspections always to
fail.

Open stderr reporting file for writing

---

openshift/inspectJob-template.yaml
openshift/inspectJobWithCPU-template.yaml

This way we can expand them in the workload operator without a need to process
template.

Keep requirements optional

---

openshift/inspectJob-template.yaml
openshift/inspectJobWithCPU-template.yaml

Issue fixed by the PR:
- Observed the `thoth-amun-inspection` namespace looks up local `inspect-hwinfo` image stream from images, whereas it should pull image from its infra environment i.e thoth-test-core.
- User has specified manually the image in the stage environment but not in the test environment.

Update job templates with imagestream info

---

amun/inspect.py

This way we will have exact datetime on when an inspection has finished -
possibility to group by datetime to see possible heavy load inference.

Capture datetime of an inspection run

---

amun/dockerfile.py
amun/inspect.py
amun/swagger.yaml

Amun specification inputs are extended with python packages
DockerFile is extended and it can install python packges if the list of python packages is not empty

Extend Amun specification and docker file

---

amun/inspect.py

Related: https://github.com/thoth-station/storages/issues/821

Propagate empty dict instead of empty string to show related exception

---

amun/dockerfile.py

Fixes: https://github.com/thoth-station/amun-api/issues/230
```
File "/opt/app-root/src/amun/dockerfile.py", line 95, in create_dockerfile
--
  | dockerfile += _determine_update_string
  | TypeError: must be str, not function
```

Fix function call

---

amun/dockerfile.py

This caused that Pipenv silently failed to parse Pipfile.lock and the whole
`pipenv install --deploy' went into a weird state causing installation issues.
This was observed only if environment markers that have quote present were used
(e.g. TensorFlow stack).

Fix escaping of quotes when writing Pipfile.lock

---

openshift/amunInspectionWorkflow-template.yaml
openshift/amunInspectionWorkflowWithCPU-template.yaml

If you have a look at one inspection workflow:
```
target:            inspection-run-result
ceph_bucket_prefix: data/thoth
ceph_bucket_name:  thoth
ceph_host:         https://s3.upshift.redhat.com/
deployment_name:   thoth-psi-stage
allowed-failures:  1
batch-size:        100
parallelism:       1
inspection-id:     inspection-cvut-6-eaf73dc5
batch-name:        {{workflow.parameters.inspection-id}}
cpu:               1
memory:            3Gi
registry:          docker-registry.default.svc:5000
thoth-infra-namespace: thoth-infra-stage
```

Parameters in Workflow template is not read

---

amun/inspect.py
workflows/templates/inspection-results-template.yaml

With this change all the results will be aggregated to a file instead of
printing them to stdout. This simplifies performance indicators handling that
were printing to stound/stderr from a forked process causing serialization
issues when the output was expected to be a JSON output (printed logs bloated
output). Also, with this fix we do not rely on OpenShift to store logs - these
logs were automatically deleted after some time causing troubles aggregating
them when they were no longer available.

Write results to file not to stdandard output

---

amun/dockerfile.py

Closes #127 
Sample docker file generated - https://paste.ofcode.org/33QsfYngtMiKcRCmA3Rn7MH
So using removing the extra `\\n`, was leading to fail for entrypoint, so I moved it to a different function and changed the `_write_file_string`. 
Ref - http://www.gnu.org/software/bash/manual/html_node/ANSI_002dC-Quoting.html
Is this the right way to do it?

Added different function for \n

---

amun/inspect.py
workflows/templates/inspection-results-template.yaml

Reverts thoth-station/amun-api#376
It turned out we cannot do it this way.
https://github.com/kubernetes/kubectl/issues/454

Revert "Write results to file not to stdandard output"

---

Pipfile
Pipfile.lock
openshift/buildConfig-template.yaml

Starting grpcio>=1.28, there is no wheel file that would match our build environment. That leads to triggering build from source that requires more resources and takes much more time in the cluster.

Pin grpcio<1.28

---

amun/inspect.py

So we do not collide with files possibly already present on the file system and
we can configure where to look for other results - e.g. amun-hwinfo files.

Make all inspection paths parametrize

---

amun/inspect.py

As we aggregate results using Argo artifacts, we do not need to print results to stdout anymore. The output of container is captured and placed on Ceph. The output can be used by libraries to produce info/warning/error messages.
With this change, we do not need to patch libraries that produced messages which verbosity was out of our control.

Do not print results to pod logs

---

amun/dockerfile.py

I experienced couple of issues with `echo -e` in Ubuntu images (`-e` is added to the output). Let's use POSIX compliant `printf`.

Avoid using echo (bashism)

---

amun/api_v1.py
amun/dockerfile.py

allow amun-api to use printf with valid delimiters
fixes: `line 0: printf: `Y': invalid format character caused by  
`\"datetime\": datetime.utcnow().strftime(\"%Y-%m-%dT%H:%M:%S.%f\")`

allow amun-api to use printf with valid delimiters

---

amun/dockerfile.py

add delimiter to the write_to_script function
Related-To: #505 
issue arise from this function, via https://github.com/thoth-station/amun-api/blob/0d7cb8671a352d9c5e98195e99b7f6ec1aa304ef/amun/dockerfile.py#L161

add delimiter to the write_to_string function

---

amun/api_v1.py

... otherwise nested entries in the specification will get escaped and stored
on Ceph (unwanted).

Perform deep copy of specification to handle escaping correctly

---

amun/entrypoint.py

When accessing Amun on "`/`" that is configured to use HTTPS route, I'm unable to see Connexion UI. The issue behind this is a wrong redirect:
```
wget https://amun.test.thoth-station.ninja 2>&1 | grep 'Location:'
Location: http://amun.test.thoth-station.ninja/api/v1/ui [following]
```
As can be seen, the redirect is not respecting HTTPS, but uses plain HTTP connecion for which we do not have any route configured.

Redirect with HTTPS if HTTPS is used

---

openapi/openapi.yaml

Related to https://github.com/thoth-station/thoth-application/issues/2496 
- No
Use the `s2i-thoth-ubi8-py38` base image as a default value in the `/inspect` endpoint. The current default value `registry.access.redhat.com/ubi8/python-36` does not have pipenv or micropipenv available, and as @fridex mentioned it would be better to use our own containerized environment to see how packages behave in them.

Use thoth-s2i image as a default value in api schema

---

openapi/openapi.yaml

Fixes schema validation that expects runtime_environment and constraints to be always present.

Make runtime_environment and constraints optional
