.zuul.yaml
=> updated to the thoth zuul jobs

amun/swagger.yaml
https://github.com/thoth-station/amun-api/issues/34
=> Added hardware specification to swagger /inspect

amun/swagger.yaml
Fixes: #58 
Introduced in https://github.com/thoth-station/amun-api/pull/46
=> Fix swagger

Pipfile, Pipfile.lock
See https://github.com/zalando/connexion#the-swagger-ui-console for more info. Otherwise Swagger UI is not present.
=> New connexion requires swagger-ui extras

amun/core.py, amun/swagger.yaml, openshift/inspectBuildConfig-template.yaml, openshift/inspectBuildConfigWithCPU-template.yaml, openshift/inspectJob-template.yaml, openshift/inspectJobWithCPU-template.yaml
Based on work done by @ace2107 
Replaces: #77
=> Add ability to specify CPU

openshift/template.yaml
=> this parameter is not required for this template

openshift/amunApiNamespace-template.yaml, openshift/amunInspectionNamespace-template.yaml
=> separated templates by namespace

openshift/amunApiNamespace-template.yaml, openshift/amunInspectionNamespace-template.yaml
=> fixing template names

amun/inspect.py
This way we will have a generic solution for gathering CPU information for any
inspection script.
Fixes: https://github.com/thoth-station/performance/issues/8
=> Use Kernel statistics to gather information about CPU utilization

openshift/deployment-template.yaml
=> namespace and tag of image to be used are now parameterizable

.zuul.yaml
=> added a build trigger to the post pipeline

openshift/deployment-template.yaml
Fixes:
- Deployment was failing as it was unable to access the image.
=> updated the image registry to the deployment

openshift/inspectJob-template.yaml, openshift/inspectJobWithCPU-template.yaml
Related: https://github.com/thoth-station/amun-api/issues/173
=> Provide default registry for inspection jobs to pull images from

amun/swagger.yaml
=> Insection typo fixed

amun/api_v1.py
Fixes: https://github.com/thoth-station/amun-api/issues/181
=> Report correct error if no log is found but job exists

amun/dockerfile.py
=> Allow empty list of native packages to be passed

openshift/inspectJob-template.yaml, openshift/inspectJobWithCPU-template.yaml
=> value: instead of default: in parameters 

amun/inspect.py
Fixes: https://github.com/thoth-station/amun-api/issues/199
=> Adjust logic for optaining CPU related statistics of the child process

README.rst
=> Added missing parameters to Amun request

openshift/deployment-template.yaml
... so that we distinguish differnet deployments
=> Propagate deployment name to deployment

amun/__init__.py, openapi/openapi.yaml, openshift/amunApiNamespace-template.yaml, openshift/amunInspectionNamespace-template.yaml, openshift/buildConfig-template.yaml, openshift/configmap-template.yaml, openshift/deployment-template.yaml, openshift/inspectBuildConfig-template.yaml, openshift/inspectBuildConfigWithCPU-template.yaml, openshift/inspectImageStream-template.yaml, openshift/inspectJob-template.yaml, openshift/inspectJobWithCPU-template.yaml, openshift/secrets-template.yaml
=> bounced all amun version strings to 0.5.0

amun/entrypoint.py
Fixes: https://github.com/thoth-station/amun-api/issues/248
=> Add Thoth-Version header

openshift/deployment-template.yaml, openshift/imagestream-template.yaml
Maintain image stream template for consistency
=> Maintain imagestream template for consistency

openshift/amunApiNamespace-template.yaml, openshift/amunInspectionNamespace-template.yaml, openshift/buildConfig-template.yaml, openshift/configmap-template.yaml, openshift/deployment-template.yaml, openshift/imagestream-template.yaml, openshift/inspectBuildConfig-template.yaml, openshift/inspectBuildConfigWithCPU-template.yaml, openshift/inspectImageStream-template.yaml, openshift/inspectJob-template.yaml, openshift/inspectJobWithCPU-template.yaml, openshift/secrets-template.yaml
updated templates with annotations and param thoth-advise-value
=> updated templates with annotations and param thoth-advise-value

amun/inspect.py
Depends-On: https://github.com/thoth-station/amun-hwinfo/pull/12
=> Standardize output for runtime environment

openapi/openapi.yaml
=> Add runtime environment

amun/dockerfile.py
modified:   amun/dockerfile.py
=> Added newlines after dockerfile update string

.gitignore, Pipfile, Pipfile.lock, amun/entrypoint.py
This is giving us a CORS header of 'allow all'
=> Feature: cors allow all

Pipfile, Pipfile.lock
=> added the missing modules

openshift/inspectImageStream-template.yaml
=> Add missing label for Amun inspection is

amun/dockerfile.py, openshift/inspectBuildConfigWithCPU-template.yaml, openshift/inspectJobWithCPU-template.yaml
- Templates updated in test environment
- Tested successfully in test environment
=> Remove node

openapi/openapi.yaml
=> Correct datatype inspection output

openapi/openapi.yaml
=> Add field and correct datatype

openapi/openapi.yaml
=> Remove line (finally)

amun/dockerfile.py
Reverts thoth-station/amun-api#296
=> Revert "Remove LC_ALL change locale warning"

openapi/openapi.yaml
=> Increase memory requiremetns for example input

amun/api_v1.py
Fixes: https://github.com/thoth-station/storages/issues/1551
=> Fix default requests assignment if None was provided on endpoint

openshift/inspectBuildConfig-template.yaml, openshift/inspectBuildConfigWithCPU-template.yaml, openshift/inspectImageStream-template.yaml, openshift/inspectJob-template.yaml, openshift/inspectJobWithCPU-template.yaml
so that we can use label selector
=> Add inspection_id label

amun/inspect.py
As discussed in #265 
modified:   amun/inspect.py
=> Changed OUTPUT_ARTIFACT to THOTH_OUTPUT_ARTIFACT

amun/api_v1.py
As discussed in #265 
modified:   amun/api_v1.py
=> Removed duplicated function definition

amun/api_v1.py, openapi/openapi.yaml
modified:   amun/api_v1.py
modified:   openapi/openapi.yaml
=> Removed InspecitonWorkflowParameters from InspectionResponse

amun/dockerfile.py
This has been already fixed, wrong rebase in bc67cd0dd2dda238b61f27b24
=> Fix dockerfile formatting

amun/api_v1.py
Depends-On: https://github.com/thoth-station/common/pull/714
=> Move workflow manager logic for amun in Openshift class

amun/api_v1.py, openapi/openapi.yaml, openshift/amunInspectionWorkflow-template.yaml, openshift/amunInspectionWorkflowWithCPU-template.yaml
modified:   amun/api_v1.py
modified:   openapi/openapi.yaml
modified:   openshift/amunInspectionWorkflow-template.yaml
modified:   openshift/amunInspectionWorkflowWithCPU-template.yaml
=> Sync workflow and document IDs

amun/api_v1.py, openapi/openapi.yaml, openshift/amunInspectionWorkflow-template.yaml, openshift/amunInspectionWorkflowWithCPU-template.yaml, workflows/templates/inspection-run-template.yaml, workflows/templates/inspection-run-with-cpu-template.yaml
* remove allowed failures configuration - will not be needed with argo
* remove parallelism configuration - will be configured on Argo level
Related: https://github.com/thoth-station/common/pull/771
=> Update inspection templates

amun/api_v1.py, openapi/openapi.yaml, openshift/amunInspectionWorkflow-template.yaml, openshift/amunInspectionWorkflowWithCPU-template.yaml, workflows/templates/inspection-run-template.yaml, workflows/templates/inspection-run-with-cpu-template.yaml
https://github.com/thoth-station/common/pull/770
=> Distinguish cpu and memory for inspection builds and runs

workflows/templates/inspection-build-template.yaml, workflows/templates/inspection-build-with-cpu-template.yaml
Otherwise result gathering fails from time to time.
=> Add new line after heredoc

Pipfile.lock
=> Relocked pipfile lock

.thoth.yaml
Allow maintainers to release the application
Related-to: #446 
=> Allow maintainers to release the application

amun/api_v1.py, amun/entrypoint.py
Fixes: https://github.com/thoth-station/amun-api/issues/466
=> Create & expose service version

amun/api_v1.py
inspectionstore has attribute build
build is the attribute present in inspectionstore
https://github.com/thoth-station/storages/blob/a68f7c601e77a33cdd2db85017e3381e34fdfe00/thoth/storages/inspections.py#L150
=> inspectionstore has attribute build

amun/api_v1.py, openapi/openapi.yaml
=> Provide an endpoint for listing available inspections

amun/api_v1.py
=> Page and limit are optional

amun/api_v1.py
=> Fix islice serialization

amun/dockerfile.py
otherwise I see the following step produced
```
STEP 5: RUN pip install --upgrade pip RUN pip3 install --force-reinstall --upgrade micropipenv[toml]
```
=> Fix generation of Dockerfile with pip upgrade

amun/api_v1.py
Depends-On: https://github.com/thoth-station/common/pull/936 https://github.com/thoth-station/common/issues/939 https://github.com/thoth-station/amun-api/pull/524
Fixes: https://github.com/thoth-station/amun-api/issues/486 https://github.com/thoth-station/amun-api/issues/487
=> Add support for raw specification

amun/api_v1.py
Related: https://github.com/thoth-station/amun-api/issues/486
=> Make sure the batch_size is always int in raw specification

amun/dockerfile.py
Fixes: https://github.com/thoth-station/amun-api/issues/539
=> Add one more escaped / when serializing files or strings

amun/inspect.py
=> Include start and end datetime of inspections

amun/api_v1.py
Fixes: https://github.com/thoth-station/amun-api/issues/549
=> Propagate Amun version into inspection metadata

amun/api_v1.py
Related: https://github.com/thoth-station/thoth-application/pull/472
=> Propagate deployment-name and Amun API url to specification

README.rst
=> Add a link to YT video with instructions how to deploy Amun

Pipfile.lock
Otherwise Amun API fails to boot.
=> Relock to fix marker issues

openapi/openapi.yaml
Depends on: https://github.com/thoth-station/common/pull/1107
I added args so that message contents and behaviour can be adjusted
=> add openshift schedule params for inspection complete message

README.rst
=> Add related links to the README

Pipfile, Pipfile.lock
Related: https://github.com/thoth-station/management-api/issues/762
=> Fix module not found error for flask._compat

.pre-commit-config.yaml, .prow.yaml, .thoth.yaml, amun/api_v1.py, amun/configuration.py, amun/dockerfile.py, amun/entrypoint.py, amun/inspect.py, mypy.ini
ci updates w.r.t prow and thoth
=> ci updates w.r.t prow and thoth

.github/CODEOWNERS, .pre-commit-config.yaml, Pipfile, Pipfile.lock, amun/configuration.py, mypy.ini
I have removed the opentracing/jaeger bits.
=> remove the tracing bits

amun/exceptions.py
=> Ignore N818

.pre-commit-config.yaml
fix the pre-commit git url issue
Related-to: https://github.com/thoth-station/thoth-application/issues/2111
=> fix the pre-commit git url issue

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/kebechet_info.md, .github/ISSUE_TEMPLATE/kebechet_update.md, .github/ISSUE_TEMPLATE/major-release.md, .github/ISSUE_TEMPLATE/minor-release.md, .github/ISSUE_TEMPLATE/patch-release.md, .github/ISSUE_TEMPLATE/redeliver_container_image.md
Include issue template for the repo
=> Include issue template for the repo

Pipfile, Pipfile.lock
Remove the unused packages
This package are no longer are being used in the application.
=> Remove the unused packages

amun/api_v1.py
Related to https://github.com/thoth-station/amun-api/issues/641#issuecomment-1041540634
- No
=> Fix NotFoundExceptionError import

openapi/openapi.yaml
Fixes: https://github.com/thoth-station/thoth-application/issues/2489
- No
=> Add runtime_environment and constraints to api schema

Pipfile, Pipfile.lock
=> Specify version range for markupsafe to fix library issues

.thoth.yaml, OWNERS
=> Add my username to approvers and maintainers

openapi/openapi.yaml
Fixes issues when validating requests from dependency-monkey.
=> Constraints key is an array
